// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslIq1sGq-ses8Dx2IEUeRcM5zeR0kLBQ',
    appId: '1:860322241467:web:74f4f460012970eedfc29e',
    messagingSenderId: '860322241467',
    projectId: 'papets-app',
    authDomain: 'papets-app.firebaseapp.com',
    storageBucket: 'papets-app.appspot.com',
    measurementId: 'G-BCL7YVZD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmSKoH8xsNJC9BByktPtbMYOyP08sRL4',
    appId: '1:860322241467:android:a2b0f92357cef4e4dfc29e',
    messagingSenderId: '860322241467',
    projectId: 'papets-app',
    storageBucket: 'papets-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR0FfculM-vohT9_yQQO4pJ0Ynz9hCNoU',
    appId: '1:860322241467:ios:e45769788727c79edfc29e',
    messagingSenderId: '860322241467',
    projectId: 'papets-app',
    storageBucket: 'papets-app.appspot.com',
    iosClientId: '860322241467-edbt0it2evh84plt66fin6p3r6ofdi86.apps.googleusercontent.com',
    iosBundleId: 'com.papets.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR0FfculM-vohT9_yQQO4pJ0Ynz9hCNoU',
    appId: '1:860322241467:ios:e45769788727c79edfc29e',
    messagingSenderId: '860322241467',
    projectId: 'papets-app',
    storageBucket: 'papets-app.appspot.com',
    iosClientId: '860322241467-edbt0it2evh84plt66fin6p3r6ofdi86.apps.googleusercontent.com',
    iosBundleId: 'com.papets.app',
  );
}
